### ISSUE TITLE
[cortex port] Return code lost across a svc

### ISSUE THREAD

**Issue by jlbirccyn** [TrampolineRTOS/trampoline#1]
In the svc handler, the return code (r0) is not copied back in the process stack.

In fact, instead of saving the return code of the service in the system stack on line 241:
```
        str r0, [r5, #KS_RETURN_CODE]
```
It could be saved on the process stack directly. The saved r0 being on the top of the process stack, the line above could be replaced by:
```
        ldr r12, [r5, #KS_PROCESS_SP]
        str r0, [r12]
```
As a result, the tpl_save_context function would not have to save the return code in the context and line 84, 85, 123 and 124 of tpl_ctx_switch.S would be deleted.

Line 318 of tpl_system_call.S would be deleted too.

**Comment by DavidGarriou** [comment]
Modification of files:
```
goil/templates/code/cortex/armv7/tpl_second_stage_irq.goilTemplate
machines/cortex/tpl_ctx_switch.S
machines/cortex/tpl_os_kernel_stack.h
machines/cortex/tpl_system_call.S
```
Add an example:
```
examples/cortex/armv7/stm32f407/stm32f4discovery/alarms
```
commit 
```
[master f8b240b]
```
with message:
```
[issue][#1][cortex port] Return code lost across a svc #1
```
