### ISSUE TITLE
Posix support with python build

### ISSUE THREAD

**Issue by LMG** [TrampolineRTOS/trampoline#10]
When using 

    BUILD = TRUE {
        SYSTEM = PYTHON;
    }

and generating the files for posix with

    goil -t=posix

we get a number of fatal errors.
 
    .../trampoline/os/tpl_os_internal_types.h:30:30: fatal error: tpl_os_std_types.h: No such file or directory
    compilation terminated.
    Return code: 1

**Comment by LMG** [comment]
Note: the errors happen when running `make.py` of course.

**Comment by jlbirccyn** [comment]
Fixed in ac99e96f2d712a5c61aadac640cb8507fc865a00
