### ISSUE TITLE
goil compilation error

### ISSUE THREAD

**Issue by wowscai** [TrampolineRTOS/trampoline#100]
When compiling goil (under MacOSX Big Sur 11.3.1), I have error during compiling. Below the output of build.py execution

makefile-macosx % ./build.py        
[  0%] Native Compiling for OS X: all-galgas.cpp
[  0%] Native Compiling for OS X: all-libpm.cpp
[  1%] Native Compiling for OS X: all-declarations-11.cpp
[  1%] Native Compiling for OS X: all-declarations-10.cpp
[  1%] Native Compiling for OS X: all-declarations-9.cpp
[  2%] Native Compiling for OS X: all-declarations-8.cpp
In file included from ../build/libpm/all-libpm.cpp:19:
[  2%] Native Compiling for OS X: all-declarations-7.cpp
../build/libpm/bdd/C_BDD-and-operation.cpp:38:15: error: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Werror,-Wnon-c-typedef-for-linkage]
typedef struct {
              ^
               tStructANDOperationCacheEntry
../build/libpm/bdd/C_BDD-and-operation.cpp:39:3: note: type is not C-compatible due to this member declaration
  public : uint64_t mOperands ;
  ^~~~~~~~
../build/libpm/bdd/C_BDD-and-operation.cpp:41:3: note: type is given name 'tStructANDOperationCacheEntry' for linkage purposes by this typedef declaration
} tStructANDOperationCacheEntry ;
  ^
1 error generated.
Return code: 1
Wait for job termination...
1 error.

gcc-v output:
makefile-macosx % gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: x86_64-apple-darwin20.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Any ideas/solution? Thank you

**Comment by jlbirccyn** [comment]
I'll check that. Unfortunately I do not have Big Sur yet.

**Comment by mbriday** [comment]
Hi,
This have been fixed in commit c1d8582.
