### ISSUE TITLE
adaptation of CHECK_ISR2_CALL_LEVEL_ERROR for trampoline multicore

### ISSUE THREAD

**Issue by atouti2000** [TrampolineRTOS/trampoline#11]
the function named CHECK_ISR2_CALL_LEVEL_ERROR(result) need to have a second parameter in multicore version.

    #if (ISR_COUNT == 0) && (WITH_OS_EXTENDED == YES)
    #   define CHECK_ISR2_CALL_LEVEL_ERROR(result)                          \
        if (result == (tpl_status)E_OK)                                     \
        {                                                                   \
            result = (tpl_status)E_OS_CALLEVEL;                             \
        }
     #endif
    
    /*  Any ISR and extended error checking (WITH_OS_EXTENDED == YES). */
    #if (ISR_COUNT > 0) && (WITH_OS_EXTENDED == YES)
    #   define CHECK_ISR2_CALL_LEVEL_ERROR(result)                          \
        if ((result == (tpl_status)E_OK) &&                                 \
            (tpl_current_os_state() != (tpl_os_state)OS_ISR2))  \
        {                                                                   \
            result = (tpl_status)E_OS_CALLEVEL;                             \
        }
    #endif
    
    /*  no extended error checking (WITH_OS_EXTENDED == NO).    */
    #if WITH_OS_EXTENDED == NO
    #   define CHECK_ISR2_CALL_LEVEL_ERROR(result)
    #endif

should be

    #if (ISR_COUNT == 0) && (WITH_OS_EXTENDED == YES)
    #   define CHECK_ISR2_CALL_LEVEL_ERROR(a_core_id, result)                          \
        if (result == (tpl_status)E_OK)                                     \
        {                                                                   \
            result = (tpl_status)E_OS_CALLEVEL;                             \
        }
     #endif    

    /*  Any ISR and extended error checking (WITH_OS_EXTENDED == YES). */
    #if (ISR_COUNT > 0) && (WITH_OS_EXTENDED == YES)
    #   define CHECK_ISR2_CALL_LEVEL_ERROR(a_core_id, result)                          \
        if ((result == (tpl_status)E_OK) &&                                 \
            (tpl_current_os_state(CORE_ID_OR_NOTHING(a_core_id)) != (tpl_os_state)OS_ISR2))  \
        {                                                                   \
            result = (tpl_status)E_OS_CALLEVEL;                             \
        }
     #endif
    
    /*  no extended error checking (WITH_OS_EXTENDED == NO).    */
    #if WITH_OS_EXTENDED == NO
    #   define CHECK_ISR2_CALL_LEVEL_ERROR(a_core_id, result)
    #endif

and  in the function tpl_terminate_isr2_service at line 215
       CHECK_ISR2_CALL_LEVEL_ERROR(result)
should be 
     CHECK_ISR2_CALL_LEVEL_ERROR(core_id, result)

**Comment by jlbirccyn** [comment]
Fixed in d681c894113300f605d1cd25c35ce8577369f662
