### ISSUE TITLE
Does trampoline  compatible with Raspberry PI 3（BCM2837）

### ISSUE THREAD

**Issue by jq12** [TrampolineRTOS/trampoline#115]
as the title

**Comment by jlbirccyn** [comment]
Hello.

No, armv8 is not supported.

For what purpose do you want to run and OSEK/AUTOSAR OS on 64 bits target ?

Best regards

**Comment by jq12** [comment]
Hi

We just take a testing on RPi 3 board. Our hardware product using heterogenous chip with arm-m4 core and arm-R core. The ultimate goals is run TramplineRTOS on arm-m4. Can you give us some advices for testing tramplineRTOS  and fits our requirements.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
