### ISSUE TITLE
Readbutton_isr example, (osConst) conflict with (osVar) 

### ISSUE THREAD

**Issue by David-Samir-Luis** [TrampolineRTOS/trampoline#119]
this error appears when executing "python make.py" in example "examples\cortex\armv7em\stm32f407\stm32f4discovery\readbutton_isr"

![IMG-20230413-WA0066](https://user-images.githubusercontent.com/85419503/231884320-a5350300-db3a-49a9-85ea-87d848f46d06.jpg)

**Comment by jlbirccyn** [comment]
An pull trampoline. The ld of gcc 10 distribution does not support an option I added to handle your previous issue.
