### ISSUE TITLE
[examples] [posix] [ioc] incorrect format specifier

### ISSUE THREAD

**Issue by szsam** [TrampolineRTOS/trampoline#125]
https://github.com/TrampolineRTOS/trampoline/blob/7ac178b0f67268735e8f9084cac49efe545ae80c/examples/posix/ioc/ioc.c#L23
https://github.com/TrampolineRTOS/trampoline/blob/7ac178b0f67268735e8f9084cac49efe545ae80c/examples/posix/ioc/ioc.c#L35

The type of `rcv_message` and `snd_message` are both `uint32`, which may be `unsigned long` or `unsigned int`. We should have a macro similar to C99's `PRIu32` for `uint32`.

**Comment by Vincent-Miao** [comment]
hi，I hava similar issues. Would it be convenient for you to leave an email address? I would like to ask your advice, thx~
