### ISSUE TITLE
Cross Compiling on Posix MACHINE

### ISSUE THREAD

**Issue by urnenfeld** [TrampolineRTOS/trampoline#13]
I have a yocto recipe which would allow to deploy Trampoline in Linux Embedded systems.
The task was a success but there was an issue which was not solved as clean as it could be.

The makefile generated by goil contains the following lines:

\#############################################################################
\# COMPILER CONFIGURATION
\#############################################################################
[...]
CC = gcc
[...]
LD = gcc
[...]
AS = gcc

These 3 statements override the environment variables set by yocto to ensure proper cross compiling. The "solution" was to remove such lines from the makefile.

Maybe the generation could be parametrized or make a weak assignment of these variables?

**Comment by jlbirccyn** [comment]
Hello. Yes we will fix that

**Comment by sefau** [comment]
This has been implemented in branch ticket13. It will be merged in the master branch after some testing.

**Comment by sefau** [comment]
Update has been merged.
If the compiler, assembler and linker are not set in the project OIL file, the value given by the environment variable CC, AS and LD will be used over the default value (gcc).

**Comment by urnenfeld** [comment]
Tested from my side. The recipe has been updated as well to fetch the new github repository & works as expected. Thanks

**Comment by jlbirccyn** [comment]
You are welcome :-)
