### ISSUE TITLE
[templates] [goil] Kernel.oil not taken into account in python build system

### ISSUE THREAD

**Issue by LMG** [TrampolineRTOS/trampoline#14]
When adding a category in goil/templates/config/kernel.oil , the python build system fails because it can not find the corresponding header files.

**Comment by jlbirccyn** [comment]
Is there a way to know if the control module is used in the OIL file ? (custom attribute of tasks ?)

**Comment by LMG** [comment]
Not as of now, but it could be added (and used for other purposes later on like locating the model description file).

**Comment by LMG** [comment]
wrong button :)

**Comment by jlbirccyn** [comment]
Ok, let's add a boolean key in the OS object to handle this case. Something like
``` 
CONTROL = TRUE;
```

**Comment by LMG** [comment]
The pull request above offers a solution, explained in [kernel module](https://github.com/TrampolineRTOS/trampoline/wiki/Kernel-modules)
