### ISSUE TITLE
How can i generate c file from oil config file ?

### ISSUE THREAD

**Issue by yousefosama654** [TrampolineRTOS/trampoline#140]

**Comment by mbriday** [comment]
Hi,
You can have a look to the documentation: [building an application](https://github.com/TrampolineRTOS/trampoline/wiki/Building-an-application).
regards

**Comment by yousefosama654** [comment]
i meant the main .c file with its static config

**Comment by jlbirccyn** [comment]
The main.c file is not generated from an OIL config.
