### ISSUE TITLE
[goil] trailing slash at the end of --target produces error

### ISSUE THREAD

**Issue by LMG** [TrampolineRTOS/trampoline#18]
$ goil --target=cortex/armv7/stm32f407/stm32f4discovery/ --templates=/home/lmg/trampoline/goil/templates/ enforcer-example-app.oil  
    /home/lmg/trampoline/goil/templates/config/cortex/armv7/stm32f407/stm32f4discovery//config.oil:3:5: semantic error #1: PATH is duplicated in file '/home/lmg/trampoline/goil/templates/config/cortex/armv7/stm32f407/stm32f4discovery/config.oil', line 3:8
    No warning, 1 error.

**Comment by jlbirccyn** [comment]
Fixed
