### ISSUE TITLE
python build system post command

### ISSUE THREAD

**Issue by mbriday** [TrampolineRTOS/trampoline#20]
The POSTCOMMAND in the python build system can be used to flash the card.
I use openOCD and the full command line would be:
```
openocd -f board/atmel_samd21_xplained_pro.cfg -c "program blink_exe verify reset exit"
```
where `blink_exe`is the executable file. But the oil description does not allow to add a ":
```
      PREOPTION = "-f board/atmel_samd21_xplained_pro.cfg -c \"program";
```

**Comment by jlbirccyn** [comment]
Fixed in 647192c4d799fbd802158b1d2930c6c38ea60c00
