### ISSUE TITLE
PROC_RUNNING, PROC_READY, PROC_WAITING and PROC_SUSPENDED does not conform to OSEK specification

### ISSUE THREAD

**Issue by jlbirccyn** [TrampolineRTOS/trampoline#22]
In OSEK OS 2.2.3 specification, section 13.2.4 (page 54) specifies the constants of type TaskStateType. Theses constants are RUNNING, WAITING, READY, SUSPENDED and INVALID_TASK. Recent commit (https://github.com/TrampolineRTOS/trampoline/commit/22fb1d96ad621430d6dfed4aa3523bfb74353d0b) breaks that.

Another way to solve the conflict with SAM D21 register fields name should be used.

**Comment by mbriday** [comment]
fixed in commit 2383e09.
SAMD21 support back in commit 11960ab
