### ISSUE TITLE
Unexisting member name "activation_allowed" in tpl_proc structure

### ISSUE THREAD

**Issue by Snakeuh** [TrampolineRTOS/trampoline#31]
In file autosar/tpl_as_app_kernel.c :
```
374           tpl_dyn_proc_table[proc_id]->activation_allowed = TRUE;
```
activation_allowed doesn't exists in the tpl_proc structure (defined in tpl_os_kernel.h).

**Comment by sefau** [comment]
Closed in commit c2fcadfcbc8dccb37bd13fb17f1bc265003a93f5

These code lines were coming from a previous implementation of the timing protection and had been forgotten when the new implementation has been done.
The reset of the task is now done in function tpl_tp_on_activate_or_release from autosar/tpl_as_timing_protec.c
