### ISSUE TITLE
The python build system calls depends on external unix tools.

### ISSUE THREAD

**Issue by mbriday** [TrampolineRTOS/trampoline#32]
The python build system call the external unix tools 'rm' and 'mkdir'. There are however a python implementation of these tools. 
This could increase the portability (windows…)

**Comment by jlbirccyn** [comment]
Made the changes and submitted them to Pierre. Waiting for its opinion.

**Comment by jlbirccyn** [comment]
Fixed in 2839a7a059914501f4bdf47ff9f7751f70a8514e
