### ISSUE TITLE
RAM size for stm32f407

### ISSUE THREAD

**Issue by LMG** [TrampolineRTOS/trampoline#38]
Hi all,

I believe the RAM size listed in memory_map.goilTemplate for the stm32f407 target is wrong.
Page 70 of [the datasheet](http://www.st.com/content/ccc/resource/technical/document/datasheet/ef/92/76/6d/bb/c2/4f/f7/DM00037051.pdf/files/DM00037051.pdf/jcr:content/translations/en.DM00037051.pdf) tells us that, starting at address 0x2000 0000, there exists 112KB or RAM followed by another 16KB.
The addresses starting from 0x2002 0000 onwards are reserved.

Indeed, the 192K bytes of SRAM advertised earlier in this document are only accurate if we account for the additional 64KB of SRAM at address 0x1000 0000. 

I believe that 192K should read 128K.

**Comment by DavidGarriou** [comment]
That is right, I delayed this fix until you saw it :-).
That is done in commit [2736d45]
