### ISSUE TITLE
build.py is badly formed when post commands are missing from oil configuration

### ISSUE THREAD

**Issue by DavidGarriou** [TrampolineRTOS/trampoline#4]
We should test if there exists a post command in configuration files otherwise the build.py script is built with:
```if make.errorCount() == 0:```
This generates an error

**Comment by jlbirccyn** [comment]
Fixed in https://github.com/TrampolineRTOS/trampoline/commit/45a06e6a5e7c364966fef6c4a4ba866f9fe75c4b
