### ISSUE TITLE
ActivateTask called from an alarm callback

### ISSUE THREAD

**Issue by KamelHacene** [TrampolineRTOS/trampoline#42]
The functional test alarms_s10 calls the ActivateTask service in an alarm callback (function test_callback_instance, file callback_instance.c). This is forbidden by AUTOSAR, we should call instead directly the activate task service. Doing so will prevent us from doing a context switch (good thing !), however it'll change the tests orders...

I'm moving away this test from the test sequence for now, i'll check into it later.

**Comment by jlbirccyn** [comment]
In fact, OSEK/VDX forbids calling all services except SuspendAllInterrupts and ResumeAllInterrupts. So this test does not conform to OSEK/VDX either.
