### ISSUE TITLE
Wrong compilation in documentation

### ISSUE THREAD

**Issue by icuadrado** [TrampolineRTOS/trampoline#43]
documentation/manual/main.pdf has all references missed.

documentation/manual has a lot of files marked to be "cleaned up before updating to gitHub"

**Comment by jlbirccyn** [comment]
Hello.

Yes. The documentation is a work in progress and have to be updated to be kept on par with the current version. Any help is welcome.

The « cleaned up before updating to gitHub » is the commit message of the last commit we did before loading the project to GitHub.
