### ISSUE TITLE
Problem in ISR1 handler code generation on Cortex

### ISSUE THREAD

**Issue by jlbirccyn** [TrampolineRTOS/trampoline#5]
When defining and ISR1 with, for instance, name `my_isr` in the OIL file, the following code is generated (here the interrupt source is the FTM0 module of the mk20dx256, check : https://github.com/TrampolineRTOS/trampoline/blob/master/goil/templates/config/cortex/armv7/mk20dx256/config.oil

* in `tpl_vectors.c`:   `(tpl_it_handler) my_isr_function,`
* in `tpl_app_config.c`: 
```
FUNC(void, OS_CODE) tpl_interrupt_source_78()
{

  my_isr_function(); 
}
```

The later is unused

I believe `tpl_vectors.c` should contain: `(tpl_it_handler) tpl_interrupt_source_78,` and `tpl_app_config.c` should contain: 
```
FUNC(void, OS_CODE) tpl_interrupt_source_78()
{
  my_isr_function(); 
  FTM0_IRQ_ClearFlag();
}
```

In addition, using `FTM0_IRQ_Handler()` instead of `tpl_interrupt_source_78()`would be nice.

**Comment by DavidGarriou** [comment]
Modifications:
```
goil/templates/code/cortex/armv7/counter_call.goilTemplate
goil/templates/code/cortex/armv7/custom_code.goilTemplate
goil/templates/code/cortex/armv7/handler_body.goilTemplate
goil/templates/code/cortex/armv7/interrupt_table.goilTemplate
goil/templates/code/cortex/armv7/tpl_first_stage_irq.goilTemplate
goil/templates/code/cortex/armv7/tpl_interrupt_vectors.goilTemplate
goil/templates/code/cortex/armv7/tpl_primary_irq.goilTemplate
goil/templates/code/cortex/armv7/tpl_second_stage_irq.goilTemplate
goil/templates/code/cortex/interrupt_table.goilTemplate
goil/templates/config/cortex/armv7/config.oil
goil/templates/root.goilTemplate
```
Commit:
``` [master 179413d]```

Message:
```[cortex] Modification of call structure for IRQ - Add multiple handle…```
