### ISSUE TITLE
Example "blink" for Rpi2 won't compile

### ISSUE THREAD

**Issue by gchamp20** [TrampolineRTOS/trampoline#61]
Hi,

Right now, the example "blink" does no compile because y commit 12e6735968f8c656db introduced `tpl_disable_os_interrupts` and `tpl_enable_os_interrupts`, but they were wrongly named ` tpl_os_disable_interrupts` and ` tpl_os_enable_interrupts` by commit b1fc96a2b55d0865322b199a4 (enable/disable and OS are swapped). This causes and undefined function error during linking.

**Comment by jlbirccyn** [comment]
Fixed by #99360c9

**Comment by jlbirccyn** [comment]
Thanks for the contribution
