### ISSUE TITLE
Example Blink for avr arduino Uno does not compile

### ISSUE THREAD

**Issue by dhardy35** [TrampolineRTOS/trampoline#63]
Hi,
During the compilation I got undefined reference to tpl_disable_os_interrupts and tpl_enable_os_interrupts. It is probably the same issue as #61 but for avr.
Regards

**Comment by jlbirccyn** [comment]
Hello,

You are right. It is fixed in commit b0efdd776d41a362aab661c5f3f8be604e357165

Best regards

**Comment by jlbirccyn** [comment]
Thanks for the contribution
