### ISSUE TITLE
"tpl_debug.c" doesn't include "tpl_os_multicore_macros.h"

### ISSUE THREAD

**Issue by paeolo** [TrampolineRTOS/trampoline#65]
The file "tpl_debug.c" makes use of the macro "GET_CURRENT_CORE_ID(core_id)"but doesn't include
"tpl_os_multicore_macros.h" where the macro is defined.

**Comment by Koryphon** [comment]
Thanks.

**Comment by jlbirccyn** [comment]
Thanks
