### ISSUE TITLE
Examples for AVR do not compile

### ISSUE THREAD

**Issue by dhardy35** [TrampolineRTOS/trampoline#66]
Hi,
All the examples for arduino uno and mega do not compile except blink for arduino uno.
It seems that it comes from APPMODE std {}; in oil files. 
In the blink example for arduino uno, std is replaced by: stdAppmode
Regards

**Comment by jlbirccyn** [comment]
Thanks for the report. It's a name conflict with the C++ std namespace. Mikaël will fix it.

Best regards

**Comment by mbriday** [comment]
Hi,
We export symbols of oil objects, and the appMode name conflicts with the C++ namespace std. It has been updated in commit ac009e4d85910b3ea86cb0d5edff9fc7c8f4b667.  
regards,
Mik
