### ISSUE TITLE
Development IDE

### ISSUE THREAD

**Issue by hisham-hussien** [TrampolineRTOS/trampoline#72]
Which IDE is Used to develop for Arduino uno with trampoline ?

**Comment by mbriday** [comment]
Hi,
Trampoline with Arduino use the same python build scripts as other targets and there is no IDE provided. The Arduino libraries should be added in Trampoline, see this [README](https://github.com/TrampolineRTOS/trampoline/tree/master/examples/avr) for the installation, the compilation and the flash process.
Regards,

**Comment by hisham-hussien** [comment]
Many Thanks
