### ISSUE TITLE
[goil templates] trace generation

### ISSUE THREAD

**Issue by LMG** [TrampolineRTOS/trampoline#8]
Adding a TRACE section to the OS config section as follows

    TRACE = TRUE {
      METHOD = FILE { NAME = "trace"; };
      FORMAT = xml;
    };

returns the following error:

     .../goil/templates/log/trace_description.goilTemplate:4:16: error #1: found the 'do' keyword, expected:
    -  the 'in' keyword
    No warning, 1 error.

while generating the project with goil.

**Comment by jlbirccyn** [comment]
Fixed in abb8f3bee360c522c8784bd4974e959073851c02

**Comment by jlbirccyn** [comment]
Oups missing sir::. Fixed in 418af5d208326bcaf1b8bcc72a90f5f666dc3fa2
