### ISSUE TITLE
arm/nxt/demo_car complain goil version dismatch

### ISSUE THREAD

**Issue by JerryFan0913** [TrampolineRTOS/trampoline#89]
I fetch latest code from master branch, and try to build this demo but get the complain like below: 

compiling goil file bluetooth2.oil
goil --target=arm/nxt --templates=/mnt/d/Work/Repo/trampoline/goil/templates  bluetooth2.oil
/mnt/d/Work/Repo/trampoline/goil/templates/root.goilTemplate:33:3:7:
semantic error #1: Goil version 3.1.11 required
  error here : "Goil version " + NEEDED_VERSION + " required"

I checked the history of trampoline/goil/templates, and seems that it requires goil 3.1.11 since 2010 Oct. Unfortunately, the goil package provided in trampoline git page is 3.1.9. Any idea to fix this? Or where I can get the latest goil?

**Comment by JerryFan0913** [comment]
Not noticed that the goil source code had been included in trampoline and can be built there. This is not a real issue actually.

**Comment by jlbirccyn** [comment]
Goil build binaries are lagging a little bit. Will try to fix that next week. Glad to see you found the sources. 

Best regards
