### ISSUE TITLE
goil Xcode project is missing project.pbxproj

### ISSUE THREAD

**Issue by andreivdev** [TrampolineRTOS/trampoline#98]
goil Cocoa app does not open any window on my M1 Mac so I wanted to run a debug build and check what's wrong.

I quickly got stuck because of this error

<img width="264" alt="image" src="https://user-images.githubusercontent.com/8058187/116004753-e2cf8000-a60c-11eb-880f-e4614c394088.png">

**Comment by jlbirccyn** [comment]
I'll check that.

**Comment by mbriday** [comment]
There was an update on commit 2624863293f67820a81ed5e7fda07480d1ade476. You may be able to compile and run on an M1 Mac (cli tool in goil/makefile-macosx and cocoa editor with the XCode project).

There are binaries provided (for OS X Silicon) and the links are on the main README.md. The binaries are **not** signed. You may self sign them or rebuild binaries from sources.

regards
